### PR TITLE
Feature/eslint

### PR DESCRIPTION
**Pull request by nodexchange**
feature: eslint adjustments for the unit tests, added build folder to the .gitignore (should be self-built or auto build in the future via GH actions). 

Note: the previous unit tests are passing but I am not sure about the 'truffle version' as it fails to compile / same as on my original branch. 

Share thoughts guys. It is a rather meaty one.

### CODE REVIEW

**Comment by Ruiub3i** [comment]
Thanks for this, our team will verify it! :)

**Comment by moshmage** [comment]
Neat PR is neat

**Comment by moshmage** [comment]
grabbing off of my chat, 
> btw @Ruivaz I was checking @nodexchange 's PR on the ESLint and something crossed my mind: should we .gitignore the build folder? (but not .npmignore)

if we do make this it would be better to have a npm script that `publish`es the repo to the npm, so it can build _before_ we publish (because, by experience, making that by hand gets old pretty quick)

Ideally we would make this on a github.yml improvement branch, so as not to impact _this_ PR, as it does fall out of the provided "user story"?

**Comment by Ruiub3i** [comment]
@moshmage we need a rebase on this :)

**Pull request merged**
